name: Run Node.js script on schedule

on:
  schedule:
  - cron: "0 * * * *"  # Run every minute (for testing)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci  # Or yarn install if you use yarn
      - name: Run the script
        run: node index.js
