name: Run index.js Every Minute

on:
  schedule:
    - cron: '*/1 * * * *'  # This cron expression runs the job every minute
  push:
    branches:
      - main  # Run the workflow only on the main branch

jobs:
  run_index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run index.js
        run: node index.js